name: Convert PUMLs to PNGs 2

on:
  workflow_dispatch:

jobs:
  plantuml_to_png:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Render PlantUML Diagrams
        run: |
          output_dir="${GITHUB_WORKSPACE}/docs/images"
          mkdir -p "$output_dir"
          find "${GITHUB_WORKSPACE}/docs/diagrams" -type f -name '*.puml' | while IFS= read -r file; do
            filename=$(basename -- "$file")
            name="${filename%.*}"
            echo "Rendering | File: $file | Output: ${output_dir}/${name}.png"
            plantuml -tpng -o "$output_dir" "$file"
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          # Check for any changes
          git add .
          git diff --staged --exit-code --quiet || (git commit -m "Auto commit by GitHub Actions" && git push)